GET http://localhost:5095/games

###
GET http://localhost:5095/games/1

###
POST http://localhost:5095/games
Content-Type: application/json

{
    "name":"Minecraft",
    "genre":"Sandbox",
    "price":29.99,
    "releaseDate":"2011-11-18"
}

###
PUT http://localhost:5095/games/1
Content-Type: application/json

{
    "name":"Final Fantasy XIVXXX",
    "genre":"Roleplaying",
    "price":59.99,
    "releaseDate":"2010-11-30"
}

###
DELETE http://localhost:5095/games/1